### ISSUE TITLE
看不了图片呢？

### ISSUE THREAD

**Issue by android-xiaowei** [loopeer/code-reader#1]
点击png图，崩溃

**Comment by ToDou** [comment]
可以看啊，你是查看图片还是说图片有什么链接点击崩溃

**Comment by ToDou** [comment]
是查看的开源项目么，还是你本地的项目，如果是开源项目，能说下地址，我下载看下

**Comment by android-xiaowei** [comment]
[https://github.com/xiaopansky/Sketch](url)
这个，download以后有个captures，里面是图片

**Comment by ToDou** [comment]
确实崩了，不过这个不是图片啊，是个.hprof文件，这个确实会蹦，我修复下，md图片我看下好像有点问题，你这个md好多嵌套的style我处理下

**Comment by ToDou** [comment]
问题已修复，可以下载最新版本看下http://fir.im/coreader 

谢谢
