### ISSUE TITLE
call by system

### ISSUE THREAD

**Issue by wimming** [loopeer/code-reader#3]
nice app! but can you let it automatically open when open a code file like .py using intentfilter?

**Comment by ToDou** [comment]
Did you mean open one package then start with one  .py file?

**Comment by wimming** [comment]
Thankyou for responsing! When I want to open a file like xxx.py, system toast me can not find an app to open this file. Can the app automatically call in this situation instead of select file manually in the app? That may be better user experience.

**Comment by ToDou** [comment]
Okay! Thanks for your suggestion.I have add the intent filter. Now you can download the newest.
