### ISSUE TITLE
does it support x86 android?

### ISSUE THREAD

**Issue by hunterzhao** [loopeer/code-reader#5]
does it support x86 android? i want to buy a x86 android pad for read code. but i am afraid it won't installed on x86 android system

**Comment by ToDou** [comment]
应该可以，到时候得看看屏幕适配问题。有问题可以提一下


2017-01-09 8:56 GMT+08:00 Jiaming Zhao <notifications@github.com>:

**Comment by hunterzhao** [comment]
尽管不做android，但还是要follow一下大神
