### ISSUE TITLE
能去掉各种响应吗

### ISSUE THREAD

**Issue by barry-ren** [loopeer/code-reader#7]
比如我安装一个软件，点击一个apk安装包，它也会响应

**Comment by ToDou** [comment]
你是说点击安装包，也被coreader打开了？

**Comment by barry-ren** [comment]
对 它可以响应各种操作，就是我点开任何文件它都响应。这是我手机系统和型号

2017年4月21日 16:54，"ToDou" <notifications@github.com>写道：

**Comment by barry-ren** [comment]
对，我点击手机任何文件 coreader 都会响应，这里是截图和我手机型号

![1](http://ol5wqvn3r.bkt.clouddn.com/github-issues-1.jpg)

![1](http://ol5wqvn3r.bkt.clouddn.com/github-issues-2.jpg)

![1](http://ol5wqvn3r.bkt.clouddn.com/github-issues-3.jpg)
