### ISSUE TITLE
从github上保存的代码一直停留在解压状态

### ISSUE THREAD

**Issue by jingsam** [loopeer/code-reader#8]
手机型号：小米Max
MIUI版本：MIUI 8开发版
Android版本：7.0
Coreader版本：1.0.2
从github上复制https://github.com/vuejs/vue，下载完之后一直停留在解压状态

**Comment by ToDou** [comment]
这个下载链接之前是代码手动拼的，没找到获取首页download的默认链接，默认一般是master啥的，所以很多分支多的项目直接那样写好像都获取不了，后面也没完善，你可以在外面下载下来解压包引入即可
-。-
你max咋升到7.0的，我也是max,开发版，刷的？

**Comment by jingsam** [comment]
下载好像是可以的，就是不能解压。手动下载是可以，但是太不方便了。
线刷的，MIUI官网上有教程

**Comment by jingsam** [comment]
现在下载zip的url是 https://codeload.github.com/vuejs/vue/zip/{branch}，可否告诉我在哪里处理下载逻辑？

**Comment by jingsam** [comment]
又仔细看了下Github API，下载链接是https://api.github.com/repos/User/repo/zipball，会自动选择默认分支，之后会有一个302跳转到https://codeload.github.com/User/repo/zip/master

**Comment by ToDou** [comment]
你看下DownloadUrlParser

**Comment by rekols** [comment]
android7.1   API改了，希望作者维护一下，同时能加入单行显示。。

**Comment by debbbbie** [comment]
呼叫作者，快支持吧~~

**Comment by MlxChange** [comment]
解压问题是由于Android7.0之后文件权限更改，目前develop分支已经支持Android7.0

**Comment by rekols** [comment]
@MlxChange 怎么解决。

**Comment by MlxChange** [comment]
@rekols  develop分支有源码，可以查看一下

**Comment by rekols** [comment]
@MlxChange   develop分支打包了么？

**Comment by MlxChange** [comment]
@rekols 目前还没有，我打包一下明天上传

**Comment by debbbbie** [comment]
@MlxChange 有打包就太好了！
